# Cloudflare Tunnel configuration
tunnel: your-tunnel-id
credentials-file: /etc/cloudflared/cert.pem

# Ingress rules for routing traffic
ingress:
  # Route traffic to GitLab server
  - hostname: gitlab.yourdomain.com
    service: http://localhost:8080
    
  # Default catch-all rule
  - service: http_status:404 