# Cloudflare Tunnel configuration
tunnel: 9cedee25-708b-49d4-bf99-34b71e14c14c
credentials-file: /Users/ajitemsahasrabuddhe/.cloudflared/9cedee25-708b-49d4-bf99-34b71e14c14c.json

# Ingress rules for routing traffic
ingress:
  # Route traffic to GitLab server
  - hostname: code-feedback.ajitem.com
    service: http://localhost:8080

  # Default catch-all rule
  - service: http_status:404